### ISSUE TITLE
Support .NET Core and a Docker image.

### ISSUE THREAD

**Issue by pauldotknopf** [danielwertheim/lightnugetserver#1]
Title says it all! It doesn't look like you are using anything specific to .NET Full framework. So, maybe just update to the latest msbuild target SDK and you can support both .NET Full framework and .NET Core.

**Comment by danielwertheim** [comment]
You mean have the LightNuGetServer project be a .NET Standard project that multitargets .NET Standard 2.0 and .NET4.7.1 and then two hosts, one pure .NET Core console that does not use Topshelf .... or?

**Comment by pauldotknopf** [comment]
Exactly.

**Comment by stefannikolei** [comment]
That is not so easy because of the usage of the Nuget.V2.Server packages. This has dependencies on owin and the "old" asp.net. It should be possible but that would not mean that it is cross platform with this change

**Comment by pauldotknopf** [comment]
Ah, I see.

I suppose there is always [Sleet](https://github.com/emgarten/Sleet).

**Comment by danielwertheim** [comment]
@reaction1989 Nope. .NET Core would be out.

@pauldotknopf I guess I could make one distro using https://hub.docker.com/r/microsoft/windowsservercore/

**Comment by danielwertheim** [comment]
@pauldotknopf Didn't know of Sleet. If it works and solves your problem then go for it! Nice with V3.

**Comment by danielwertheim** [comment]
Since not possible at the moment, I'll close this one for now.
